command:
- uvicorn
- app:app
- --host
- 0.0.0.0
- --port
- '8000'
env:
- name: DATABRICKS_APP_PORT
  value: '8000'
- name: DATABRICKS_WAREHOUSE_ID
  value: 89b66b8c215e27e1
- name: STATIC_FILES_PATH
  value: /Workspace/Users/rinitlulla18@gmail.com/apps/ai-parse-demo/static
- name: NEXT_PUBLIC_API_URL
  value: https://ai-parse-demo-7474647534040832.aws.databricksapps.com
- name: DATABRICKS_VOLUME_PATH
  value: /Volumes/workspace/ai_parse_document_demo/ai_parse_job_enhanced/
- name: DATABRICKS_DELTA_TABLE_PATH
  value: workspace.ai_parse_document_demo.ai_parse_documents
- name: BATCH_INPUT_VOLUME_PATH
  value: /Volumes/workspace/ai_parse_document_demo/ai_parse_document_app_workflow/inputs/
- name: BATCH_JOB_NAME
  value: ai_parse_document_app_workflow
runtime: python_3.10
