command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
runtime: python_3.10
env:
- name: "DATABRICKS_WAREHOUSE_ID"
  value: "02804c29f542248b"
- name: "DATABRICKS_VOLUME_PATH"
  value: "/Volumes/corp_enit_sandbox_catalog/data_classification_poc/data/"
- name: "DATABRICKS_DELTA_TABLE_PATH"
  value: "corp_enit_sandbox_catalog.data_classification_poc.doc_results"
